# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require "ap"
require "bundler"

Bundler.require

module Helpers
  def class_including(mod)
    Class.new.tap {|c| c.send :include, mod }
  end
end

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

def spec_db
    "sqlite://spec/db/sequel_driver.sqlite3"
end
def sqlite_store_setup
  url = spec_db 
  catch_all_config = [ {url: url } ]
  Sandthorn.configuration = catch_all_config
  migrator = UpptecEventSequelDriver::Migration.new url: url
  migrator.send(:clear_for_test)
end